### ISSUE TITLE
Auto update/refresh

### ISSUE THREAD

**Issue by chmichael** [osmosis-labs/osmosis-info#1]
Hello,
  Please make it real time or if it isn't possible add auto refresh timer!
  
  Thank you

**Comment by IbrarMakaveli** [comment]
Hi,

It is taken into consideration, we will add a refresh every "30 seconds in the background".
Thanks for your feeback.

**Comment by jblbit** [comment]
Hi @IbrarMakaveli , would really love to help contribute to Osmosis, can you provide some pointers and more details of this feature?

**Comment by chmichael** [comment]
> It is taken into consideration, we will add a refresh every "30 seconds in the background". Thanks for your feeback.

Well ? :)

**Comment by IbrarMakaveli** [comment]
I close this issue, we will open it again when we have the real time but I think it goes without saying to refresh the data with the real time
