### ISSUE TITLE
Display more decimal points for price values that are too small: On the graph and the table (ex: BOOT, HUAHUA, STARS etc...)

### ISSUE THREAD

**Issue by IbrarMakaveli** [osmosis-labs/osmosis-info#16]
Display more decimal points for price values that are too small: On the graph and the table (ex: BOOT, HUAHUA, STARS etc...

**Comment by lebascou** [comment]
@IbrarMakaveli referencing this quick fix PR here
https://github.com/osmosis-labs/osmosis-info/pull/18
