### ISSUE TITLE
More rich data for Osmosis Pairs

### ISSUE THREAD

**Issue by 0xkrane** [osmosis-labs/osmosis-info#22]
Currently, pairwise data showcases the following (example [here](https://info.osmosis.zone/pool/1)):

- Exchange rate between the components of a pair
- Liquidity in USD terms
- Trading volume in USD terms

Think we could get more insightful data for liquidity if we also have a plot for number of LP shares that exist across time. So, a sense of whether people are adding or removing liquidity over a period of time. This disentangles the relationship between the amount of liquidity available and the price of the tokens in the pool.

For trading volume, would love to see the directionality of swaps. So for example, how much OSMO was bought in the OSMO-ATOM pool and also how much ATOM was bought up each day. 

Also thanks for the great work you guys are doing with providing analytics for osmosis! really appreciate it!

**Comment by DLatouche** [comment]
Thanks you for your feedback.
We add this on our todo list and when it will ready we will deploy it.
