### ISSUE TITLE
Typo on the new dashboard page

### ISSUE THREAD

**Issue by RoboMcGobo** [osmosis-labs/osmosis-info#35]
![image](https://user-images.githubusercontent.com/95544279/166330871-69248237-30d8-4d8f-a43b-fc172d89070c.png)

"Stacking Rewards" should be "Staking Rewards"

**Comment by jonator** [comment]
I'd also note that "Trading History" above the table, and "Trades" in the dropdown is more correct.

<img width="569" alt="Screen Shot 2022-05-02 at 5 21 03 PM" src="https://user-images.githubusercontent.com/4606373/166336380-da684906-8156-434c-8227-ed6f79e84299.png">

**Comment by IbrarMakaveli** [comment]
Correct https://github.com/osmosis-labs/osmosis-info/commit/373340dfd111c8e5c7d07a9335c94b64c4a1120f
