### ISSUE TITLE
Dashboard -> Transactions crash

### ISSUE THREAD

**Issue by jonator** [osmosis-labs/osmosis-info#40]
### Problem
Immediately after connecting my wallet, I get a white-out crash and the following error:

<img width="518" alt="Screen Shot 2022-05-25 at 8 30 26 PM" src="https://user-images.githubusercontent.com/4606373/170397359-2f76b949-3867-4593-aecd-db3c825624a7.png">

**Comment by DLatouche** [comment]
Is it still relevant or it's fixed by the new deployment ?
Have you the same issue on preproduction (https://osmosis.latouche.dev/) ?
If yes, what is the address used ? Thanks
