### ISSUE TITLE
Liquidity Rewards can't change of asset after clicking on Luna.

### ISSUE THREAD

**Issue by iam-agf** [osmosis-labs/osmosis-info#43]
When you connect the wallet to the info, then Dashboard -> Analytics -> Liquidity pool, you see this:

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/61362029/173289624-02bd4fab-5587-4240-aac7-11c37a201bf7.png">

But after you click Luna asset, it shows this view:

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/61362029/173289919-7d45dfa7-9a9e-4ff8-829a-117d116e1522.png">

The problem is that you can't change of asset anymore because the view is essentially dead, so you have to refresh the website.

---

**Device:** Macbook Air M1
**Browser:** Google Chrome

**Comment by DLatouche** [comment]
Thank you for yours feedbacks.
That will be fixed in the next release .
