### ISSUE TITLE
Pools settings don't keep state if cancelled

### ISSUE THREAD

**Issue by iam-agf** [osmosis-labs/osmosis-info#44]
When you're in pools ( [https://info.osmosis.zone/pools](https://t.co/QAXN2jI7vL) ) 
Go to the settings in the corner. Just for the example, turn on all the columns and click the boxes to check. Now all the columns are visible and the checkboxes of the columns are on in settings. 

![telegram-cloud-photo-size-1-5562007031305578419-y](https://user-images.githubusercontent.com/61362029/173290534-11f51db1-f75d-4760-8923-4db527d97fa2.jpg)

Now open the settings again and turn off all of them, but don't click the check mark, instead click the X. Obviously the columns will stay. But if you open settings again, you see that all the checkboxes are now like turned off. If the state of the settings didn't change, the checkboxes should stay in the same state they were.

---

**Device:** Macbook Air M1
**Browser:** Google Chrome

**Comment by DLatouche** [comment]
Thank you again for yours feedbacks.
That will be fixed in the next release.
