### ISSUE TITLE
"Show more" buttons are inverted in search bar.

### ISSUE THREAD

**Issue by iam-agf** [osmosis-labs/osmosis-info#46]
The button in the circle works for the table the arrow points. It shouldn't work that way.

![telegram-cloud-photo-size-1-5564333645154592722-y](https://user-images.githubusercontent.com/61362029/173291658-130ba114-00c1-453e-9177-6fe7868bf5a4.jpg)

---
**Device:** Macbook Air M1
**Browser:** Google Chrome

**Comment by iam-agf** [comment]
@DLatouche is this bug already solved? Please tell me when the next is the next update released so I can help checking here again (if you want, of course).

**Comment by DLatouche** [comment]
I don't have the exact date, but our team is testing on its side, once validated, we will deploy. I will mention you when that is done. Thank you again 👍
