### ISSUE TITLE
Dashboard-Trades crashes if no wallet.

### ISSUE THREAD

**Issue by iam-agf** [osmosis-labs/osmosis-info#47]
It seems the Dashboard->Trades tab crashes when you don't have a wallet connected. It should have a _kinder_ reaction if there's no wallet.

<img width="552" alt="image" src="https://user-images.githubusercontent.com/61362029/173294319-3831a0dc-157f-4832-9957-d29b95022046.png">

---
**Device: ** Macbook Air M1
**Browser:** Google Chrome

**Comment by DLatouche** [comment]
Thank you again for yours feedbacks.
That will be fixed in the next release.
