### ISSUE TITLE
Seach input Watchlist not working properly.

### ISSUE THREAD

**Issue by iam-agf** [osmosis-labs/osmosis-info#48]
Essentially is the same as with the search button, but with the watchlist.

<img width="791" alt="image" src="https://user-images.githubusercontent.com/61362029/173295633-a726fd5c-36ed-4d25-9107-6aca379d27d2.png">

The issues are similar to issues: 

- [x] https://github.com/osmosis-labs/osmosis-info/issues/45
- [x] https://github.com/osmosis-labs/osmosis-info/issues/46

---

**Device:** Macbook Air M1
**Browser:** Google Chrome

**Comment by iam-agf** [comment]
This issue appear in all the search inputs, like the one in the header, so I'm not sure if I should raise a separate issue for it.
<img width="847" alt="image" src="https://user-images.githubusercontent.com/61362029/173298451-e9b94a9f-9b7d-4e09-a197-edbce942fb9a.png">

**Comment by DLatouche** [comment]
It was not a bug, I think you were in Frontier app and it didn't has osmo token (only on app). But now on Frontier we have all token and that work fine.
Thank you again for all feedbacks
