### ISSUE TITLE
IBC status search error with pagination.

### ISSUE THREAD

**Issue by iam-agf** [osmosis-labs/osmosis-info#49]
In IBC Status, go to any page that isn't the first one (for the example, I used the page 3). Then in "Search IBC by token name", put any token chain except osmo. 
<img width="540" alt="image" src="https://user-images.githubusercontent.com/61362029/173297811-0bba0a50-7e13-4b68-af79-c89cda9dc7b3.png">

You can see that the list is empty BECAUSE we're in page 3, not 1. (I reduced the height of the table to show the filling of the search bar and the wrong page not being updated) 
<img width="847" alt="image" src="https://user-images.githubusercontent.com/61362029/173297975-9244b747-4072-401e-9ee1-830a41af3164.png">

---

**Device:** Macbook Air M1
**Browser:** Google Chrome

**Comment by DLatouche** [comment]
Thank you again for yours feedbacks.
That will be fixed in the next release.
