### ISSUE TITLE
Data Missing in Analytics Interface and APIs

### ISSUE THREAD

**Issue by shaggoththebig444** [osmosis-labs/osmosis-info#5]
There seems to be (price) data missing for the 13th and 14th November. Neither the interface nor the API shows it for all the coins I have checked. Woud be awesome to have that back! Best.

**Comment by IbrarMakaveli** [comment]
Hey, Thanks for pointing this out, it's corrected for 7d today and the one day candles will be redone tomorrow at midnight.

**Comment by shaggoththebig444** [comment]
Thanks man! Will it be corrected here too?

https://api-osmosis.imperator.co/tokens/v1/historical/osmo/chart?range=7d

That'd be lovely! Best.

**Comment by IbrarMakaveli** [comment]
Yes, all correct now ! Thanks you !
