### ISSUE TITLE
Osmosis Info - Click on "Top Movers" tokens

### ISSUE THREAD

**Issue by Traumz** [osmosis-labs/osmosis-info#51]
Adding the possibility to click on each tokens in the "Top Movers" scrolling menu, in order to arrive on its chart

![image](https://user-images.githubusercontent.com/98484053/190924675-10856343-a7b9-413e-96b9-1bbc3e415690.png)

**Comment by Stphill0** [comment]
Hi @Traumz kindly visit the official [COSMOS](https://cosmo-official.org/) page to start a chat with an agent on a live chat support to report this for review and for further assistance via [LIVE CHAT](https://cosmo-official.org/)

**Comment by DLatouche** [comment]
Thanks for your comment, we have implemented this, it will be online in the next deployment.
